set-option -g default-shell /bin/zsh
set -g mouse on

bind -T root F12  \
  set prefix None \;\
  set key-table off \;\
  set status-style "fg=black,bg=yellow" \;\
  if -F '#{pane_in_mode}' 'send-keys -X cancel' \;\
  refresh-client -S \;\

bind -T off F12 \
  set -u prefix \;\
  set -u key-table \;\
  set -u status-style \;\
  refresh-client -S

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

unbind C-z
bind S suspend-client

set -g status-position top
set -g status-style "bg=color134"
set -g pane-active-border-style 'fg=color134,bg=colour236'